name: CI  # Name of the workflow for continuous integration

# Triggers the workflow on pushes and pull requests to any branch
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the OS for the test environment

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v3  # Updated checkout action to v3

      # Step 2: Set up Python environment for the workflow
      - name: Set up Python
        uses: actions/setup-python@v3  # Updated Python setup action to v3
        with:
          python-version: '3.x'  # Specifies a Python 3 version; defaults to the latest 3.x version

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip to the latest version
          pip install -r requirements.txt  # Installs all required packages from requirements.txt
          pip install coverage  # Ensures coverage package is available

      # Step 4: Run tests with coverage
      - name: Run tests with coverage
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings  # Sets the Django settings module for proper configuration
        run: |
          coverage run --source='.' manage.py test blog  # Runs tests with coverage on the 'blog' app
          coverage html  # Generates HTML report of coverage

      # Step 5: Upload HTML coverage report as an artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3  # Updated to v3 to avoid deprecation
        with:
          name: coverage-report
          path: htmlcov  # Path to the HTML report directory
