# .github/workflows/ci.yml
name: CI  # Name of the workflow for continuous integration

# Triggers the workflow on pushes and pull requests to any branch
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the OS for the test environment

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v2  # This action checks out the repository code to the runner

      # Step 2: Set up Python environment for the workflow
      - name: Set up Python
        uses: actions/setup-python@v2  # Official action to set up a Python version
        with:
          python-version: '3.x'  # Specifies a Python 3 version; defaults to the latest 3.x version

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip to the latest version
          pip install -r requirements.txt  # Installs all required packages from requirements.txt

      # Step 4: Run tests using Django’s test runner
      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: mysite.settings  # Sets the Django settings module for proper configuration
        run: |
          python manage.py test  # Runs all tests in the project using Django's test runner
