# .github/workflows/ci.yml
name: CI  # Continuous Integration workflow for testing

# Run this workflow on push and pull requests for any branch
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the code from the repository
      - uses: actions/checkout@v2  # Checkout action to pull code from repo

      # Step 2: Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify a Python 3.x version

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Update pip
          pip install -r requirements.txt  # Install project dependencies

        # Step 4: Run tests with coverage
      - name: Run tests with coverage
        env:
            DJANGO_SETTINGS_MODULE: mysite.test_settings  # Ensure it uses test_settings
        run: |
            coverage run --source='.' manage.py test blog  # Runs tests with coverage on the 'blog' app
            coverage html  # Generates HTML report of coverage
